### ISSUE TITLE
Switching role

### ISSUE THREAD

**Issue by jeanmonod** [sephii/taxi-zebra#21]
When taxi asked my if I want to assign an activity to a role:

![image](https://user-images.githubusercontent.com/114489/94389900-64336280-0151-11eb-9970-ef3d2bee76b9.png)

I mostly say no, because there are no easy way to change my mind... But this is sad, because I have to answer again and again the same questions...

(In the screenshot above, I use my BizDev role, because I working on recruiting a new bizdev. This will be the case for the next weeks/months, but it will no more be the case in 3 months...)

Can we imagine some alternative? What I can think about are:

* One more option, "Yes remember it for the next XX days", so that I can safely save it for 1 week or 1 months
* One more option, "Yes, but ask me to confirm anyway", so that on the next activity usage I can just type enter to confirm it

WDYT?

**Comment by jeanmonod** [comment]
One suggestion from Tom:

* Have a new option `yes but ask from [c]onfirmation`. This would allow to set a role, use it in 90% of the case, and if during the confirmation, you decide to pick an other role, then you go again on the normal process

**Comment by sephii** [comment]
If I understand you use case correctly, you'd like to avoid having to enter the role to use on a given activity, while being able to change it at some point.

I think the role selector shouldn't be more difficult to use as it is now (it would also not be that easy to implement this new "ask for confirmation" option). I think an easier (and more elegant) way to solve your problem would be to propose a default role for the "Select a role" question, which would be the role you used in your last timesheet on this activity.

That way, you would answer "Never" when getting asked for always using this role, and you'd just have to hit "enter" on the role selection on subsequent pushes on this activity. And when you want to change it, you'll just select a different role instead of hitting "enter".

This would require having a new Zebra endpoint, which would take an activity id, and return either the last role id used for this activity, or the last X timesheets created with this activity (and taxi-zebra would then take the most recent one and extract the role id from it).

What do you think?

**Comment by jeanmonod** [comment]
That's how it work right now on Zebra (it remember the previously entered role) so yes your proposal makes sens. 

What do you exactly need?

     /GET /activity/used      => [{id: 1234, name: 'Activity 1', last-usage: '2020-09-29', role-used: 167 }, {}]

Something like that?

**Comment by sephii** [comment]
Exactly, this would be perfect.

**Comment by jeanmonod** [comment]
@sephii Here we are: https://zebra.liip.ch/api/#!/Activities/get_latestActivityRoles I make it very simple. It's just a map activityId => roleId. Tell me if you need more...
